version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: hugecookie
      POSTGRES_PASSWORD: 1331
      POSTGRES_DB: postgresdb
    ports:
      - '5432:5432'
